# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - 
       name: Download and Extract Dependencies 
       run: |
         curl https://github.com/opencv/opencv/releases/download/4.5.1/opencv-4.5.1-dldt-2021.2-vc16-avx2.zip -o opencv.zip -L
         tar -xf opencv.zip -C ${{github.workspace}}
         git clone https://github.com/google/glog.git
         cd glog
         git checkout c8f8135a5720aee7de8328b42e4c43f8aa2e60aa
         cd ..
         git clone https://gitlab.com/libeigen/eigen.git
         cd eigen
         git checkout 3.3.2
         cd ..
         git clone https://github.com/glfw/glfw.git
         cd glfw
         git checkout 3.3.2
         cmake -E make_directory ${{github.workspace}}/glfw/build
         cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install-glfw -DBUILD_SHARED_LIBS=TRUE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
         cmake --build build --target INSTALL --config Release
      
      - name: Build OmniPhotos
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cmake -S . -B build -DEIGEN_INCLUDE_DIR:PATH=${{github.workspace}}/eigen -DOpenCV_DIR:PATH=${{github.workspace}}/opencv/build/cmake -Dglfw3_DIR:PATH=${{github.workspace}}/install-glfw/lib/cmake/glfw3 -DWITH_TEST=TRUE -DWITH_OPENVR=TRUE -DWITH_GFLAGS=FALSE -DBUILD_GMOCK=FALSE -DBUILD_TESTING=FALSE
          cmake --build build --config Release
      
      - name: Download data and run tests
        run: |
          curl https://github.com/cr333/OmniPhotos/releases/download/v1.0/OmniPhotos-test-data.zip -o testDatasets.zip -L
          tar -xf testDatasets.zip -C ${{github.workspace}}
          cd opencv/build/bin/
          ${{github.workspace}}/build/Release/Test.exe -f ${{github.workspace}}/testDatasets/
          
