# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      -
        name: Choco install opencv
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install opencv --yes #--execution-timeout=30

      # Runs a set of commands using the runners shell
      - name: Download and extract eigen
        run: |
           curl https://gitlab.com/libeigen/eigen/-/archive/3.3.9/eigen-3.3.9.zip
           tar -xf eigen-3.3.9.zip .


