# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - 
       name: Download and Extract OpenCV
       run: |
         curl https://github.com/opencv/opencv/releases/download/4.5.1/opencv-4.5.1-dldt-2021.2-vc16-avx2.zip -o opencv.zip -L
         tar -xf opencv.zip -C ${{github.workspace}}
      
      - name: Clone glog
        run: |
          git clone https://github.com/google/glog.git
          cd glog
          git checkout c8f8135a5720aee7de8328b42e4c43f8aa2e60aa

      - name: Clone eigen
        run: |
          git clone https://gitlab.com/libeigen/eigen.git
          cd eigen
          git checkout 3.3.2
      
      - name: Clone GLFW
        run: |
          git clone https://github.com/glfw/glfw.git
          cd glfw
          git fetch --all --tags
          git checkout 3.3.2

      - name: build GLFW
        working-directory: ${{github.workspace}}/glfw
        run: |
          cmake -E make_directory ${{github.workspace}}/glfw/build
          cmake -S . -B build -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install-glfw -DBUILD_SHARED_LIBS=TRUE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
          cmake --build build --target INSTALL --config release
      
      - name: build Omniphotos
        run: |
          cmake -E make_directory ${{github.workspace}}/build
          cmake -S . -B build -DEIGEN_INCLUDE_DIR:PATH=${{github.workspace}}/eigen -DOpenCV_DIR:PATH=${{github.workspace}}/opencv/build/cmake -Dglfw3_DIR:PATH=${{github.workspace}}/install-glfw/lib/cmake/glfw3 -DWITH_TEST=TRUE -DWITH_OPENVR=TRUE -DWITH_GFLAGS=FALSE -DBUILD_GMOCK=FALSE -DBUILD_TESTING=FALSE
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1
      
      - name: Build
        run: msbuild /m /p:Configuration=Release build\Omniphotos.sln 
        
